name: continuous_integration_build
on:
  push:
    branches: ["core"]
  pull_request:
    branches: ["*"]
env:
  target_device_version: 15.5
jobs:
  continuous_integration_build:
    runs-on: macos-latest
    steps:
    - name: checkout:sine_generator
      uses: actions/checkout@v5
      with:
        path: sine_generator
    - name: checkout:clic3
      uses: actions/checkout@v5
      with:
        repository: alic3dev/clic3
        path: clic3
    - name: checkout:math_c
      uses: actions/checkout@v5
      with:
        repository: alic3dev/math_c
        path: math_c
    - name: make:clic3
      run: cd clic3 && make clic3_dylib target_device_version=${{ env.target_device_version }}
    - name: make:math_c
      run: cd math_c && make math_c_dylib target_device_version=${{ env.target_device_version }}
    - name: make:sine_generator
      run: cd sine_generator && make target_device_version=${{ env.target_device_version }}
